services:
  site1:
    build: ./site1
    container_name: site1
    ports:
      - "8081:80"
    networks:
      - sites-net

  site2:
    build: ./site2
    container_name: site2
    ports:
      - "8082:80"
    networks:
      - sites-net

networks:
  sites-net:
    driver: bridge
