name: Backup arquivo SQL

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  backup:
    runs-on: self-hosted
    steps:
      - name: Nome do arquivo
        id: nome
        run: echo "arquivo_sql=backup-$(date +%Y%m%d-%H%M%S).sql" >> $GITHUB_OUTPUT

      - name: Criar pasta de backups
        run: mkdir -p ~/backups-postgres

      - name: Gerar dump do Postgres
        run: |
          docker exec cadastro-db pg_dump -U admin -d usuarios \
          > ~/backups-postgres/${{ steps.nome.outputs.arquivo_sql }}

      - name: Enviar backup para o S3
        run: |
          aws s3 cp ~/backups-postgres/${{ steps.nome.outputs.arquivo_sql }} \
            s3://backups-db-cadastro-de-usuarios/ --region us-east-2

      - name: Limpar backup antigos
        run: |
          cd ~/backups-postgres
          rm -rf *