name: backup arquivo python

jobs:
  backup-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Backup arquivo python
        run: |
          mkdir -p backup
          cp aplicacao-python/app.py backup/app$(date +%Y%m%d%H%M%S).py

      - name: Commit and push backup
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "henrique_gmal@hotmail.com""
          git add .
          git commit -m "Backup do arquivo python em $(date +%Y-%m-%d %H:%M:%S)"
          git push origin main  