name: Build Docker image

on:
  push:
    branches:
      - main
    paths:
      - 'novo-site/**'
  workflow_dispatch:
    inputs:

jobs:
  build:
    runs-on: ubuntu-latest ### maquina virtual para rodar o processo de build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detectar mudanças nos projetos
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            novo-site:
              - 'novo-site/**'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build novo-site
        if: |
          (github.event_name != 'workflow_dispatch' && steps.changes.outputs.site == 'true') ||
          (github.event_name == 'workflow_dispatch' && github.event.inputs.projeto == 'site')
        run: |
          cd site
          docker build -t meu-site:${{ github.event.inputs.ambiente || 'dev'}} .
          echo "Imagem do site buildada!"
          docker images meu-site:${{ github.event.inputs.ambiente || 'dev'}}
          docker inspect meu-site:${{ github.event.inputs.ambiente || 'dev'}}
