name: Build Docker novo-site

on:
  push:
    branches:
      - main
    paths:
      - 'novo-site/index.html'
      - 'novo-site/style.css'
      - 'novo-site/script.js'
      - 'novo-site/Dockerfile'
      - '.github/workflows/build-docker-novo-site.yaml'
  workflow_dispatch:
    inputs:
      ambiente:
        description: 'Ambiente de build (dev, staging, prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build novo-site
        run: |
          cd novo-site
          docker build -t meu-novo-site:${{ github.event.inputs.ambiente || 'dev' }} .
          echo "Imagem do novo-site buildada!"
          docker images meu-novo-site:${{ github.event.inputs.ambiente || 'dev' }}
          docker inspect meu-novo-site:${{ github.event.inputs.ambiente || 'dev' }}
