name: Build Docker image

on:
  push:
    branches:
      - main
    paths:
      - 'aplicacao-python/**'
      - 'site/**'
  pull_request:
    branches:
      - main
    paths:
      - 'aplicacao-python/**'
      - 'site/**'
  workflow_dispatch:
    inputs:
      ambiente:
        description: 'Ambiente de build (dev, staging, prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod
      projeto:
        description: 'Projeto para build (aplicacao-python, site)'
        required: true
        default: 'aplicacao-python'
        type: choice
        options:
          - aplicacao-python
          - site

jobs:
  build:
    runs-on: ubuntu-latest ### maquina virtual para rodar o processo de build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detectar mudanças nos projetos
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            python:
              - 'aplicacao-python/**'
            site:
              - 'site/**'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build aplicacao-python
        if: |
          (github.event_name != 'workflow_dispatch' && steps.changes.outputs.python == 'true') ||
          (github.event_name == 'workflow_dispatch' && github.event.inputs.projeto == 'aplicacao-python')
        run: |
          cd aplicacao-python
          docker build -t minha-imagem-python:${{ github.event.inputs.ambiente || 'dev'}} .
          echo "Imagem Python buildada!"
          docker images minha-imagem-python:${{ github.event.inputs.ambiente || 'dev'}}
          docker inspect minha-imagem-python:${{ github.event.inputs.ambiente || 'dev'}}

      - name: Build site
        if: |
          (github.event_name != 'workflow_dispatch' && steps.changes.outputs.site == 'true') ||
          (github.event_name == 'workflow_dispatch' && github.event.inputs.projeto == 'site')
        run: |
          cd site
          docker build -t meu-site:${{ github.event.inputs.ambiente || 'dev'}} .
          echo "Imagem do site buildada!"
          docker images meu-site:${{ github.event.inputs.ambiente || 'dev'}}
          docker inspect meu-site:${{ github.event.inputs.ambiente || 'dev'}}
