name: Exercicio 3

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest ### maquina virtual para rodar o processo de build
    steps:
      - name: checkout do codigo
        uses: actions/checkout@v4

      - name: Verifique se existe README.md.
        run: |
          if [ -f README.md ];then
            echo "Arquivo README.md encontrado!"
          else
            echo "Nenhum arquivo README.md encontrado."
          fi
      
      - name: Verifique se existe Dockerfile, se existir
        run: |
          if [ -f Dockerfile ];then
            echo "Arquivo Dockerfile encontrado!"
          else
            echo "Nenhum arquivo Dockerfile encontrado."
          fi  

      - name: Se existir um arquivo README.md ou Dockerfile mostre uma mensagem de Sucesso
        run: |
          if [ -f README.md ] || [ -f Dockerfile ];then
            echo "Arquivo README.md ou Dockerfile encontrado!"
          else
            echo "Nenhum arquivo README.md ou Dockerfile encontrado."
          fi                      
          
             
                      

      
             


      