name: Exercicio 1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest ### maquina virtual para rodar o processo de build
    steps:
      - name: checkout do codigo
        uses: actions/checkout@v4

      - name: Mostre a data e hora
        run: |
          date

      - name: Mostre o usuario atual
        run: |
          whoami    

      - name: Mostre o diretorio atual
        run: |
          pwd

      - name: Listar arquivos do projeto
        run: |
          ls -la

      - name: Mostre o conteudo README.md, se existir
        run: |
          cat README.md
          
                      